.\" Manpage for display_info.
.TH display_info "2022-10-27" "X OSD Library"
.SH NAME
display_info \- gives information about the current display
.SH SYNOPSIS
int display_info()
.SH DESCRIPTION
display_info generates the information that is placed onto the display
.SH ARGUMENTS
Takes no arguments
.SH RETURN VALUE
returns 1 on success
.SH AUTHOR
libXosd team at Western Washington University