.\" Manpage for display_info.
.TH display_info "2022-10-27" "X OSD Library"
.SH NAME
display_info \- displays information about the current display using the libxosd library
.SH SYNOPSIS
int display_info()
.SH DESCRIPTION
\fBdisplay_info\fR retrieves the specifications of the screens on the X11 connection and displays them on screen.
Like \fBosd_cat\fR(1xosd), \fBdisplay_info\fR is a tool to be used on its own, and it will display the number 
of each monitor as well as the resolution of that monitor in the corner.
.SH ARGUMENTS
Takes no arguments
.SH RETURN VALUE
returns 0 on success, -1 otherwise
.SH AUTHOR
libXosd team at Western Washington University
