.\" Manpage for display_info.
.TH display_info "2022-10-27" "X OSD Library"
.SH NAME
display_info \- displays information about the current display using the libxosd library
.SH SYNOPSIS
int display_info()
.SH DESCRIPTION
\fBdisplay_info\fR retrieves the specifications of the screens on the X11 connection and displays them on screen.
It is a tool that is similar to \fBosd_cat\fR(1xosd).
.SH ARGUMENTS
Takes no arguments
.SH RETURN VALUE
returns 0 on success, -1 otherwise
.SH AUTHOR
libXosd team at Western Washington University
