.\" Manpage for osd_split.
.TH osd_split "2022-10-27" "X OSD Library"
.SH NAME
osd_split \- splits the display into multi-monitor display
.SH SYNOPSIS
void* osd_split()
.SH DESCRIPTION
osd_split splits the display into the desired number of different screen displays
.SH ARGUMENTS
Takes no arguments
.SH AUTHOR
libXosd team at Western Washington University