.\" Manpage for osd_split.
.TH osd_split "2022-10-27" "X OSD Library"
.SH NAME
osd_split \- main function for applying work of threads for screen dispay
.SH SYNOPSIS
void* osd_split()
.SH DESCRIPTION
osd_split is the work that various threads are undergoing in order to display screen information.
This concerns things such as the alignment, position of the screen, and where to place the xosd 
window to correspond with the desired screen display.
.SH ARGUMENTS
Takes no arguments
.SH AUTHOR
libXosd team at Western Washington University