.\" Manpage for screen_count.
.TH screen_count "2022-11-04" "X OSD Library"
.SH NAME
screen_count \- gives number of back-end screens
.SH SYNOPSIS
int screen_count(xosd * osd)
.SH DESCRIPTION
screen_count gives an integer representing the number of screens on the X11 connection
.SH ARGUMENTS
Takes xosd * osd as an argument, representing the X11 connection
.SH RETURN VALUE
Returns nscreens, which is the number of back-end screens i.e. physical monitors or analogues
.SH AUTHOR
libXosd team at Western Washington University
