.\" Manpage for screen_count.
.TH screen_count "2022-10-27" "X OSD Library"
.SH NAME
screen_count \- gives number of screens
.SH SYNOPSIS
int screen_count(xosd *osd)
.SH DESCRIPTION
screen_count gives an integer representing the current number of screen displays
.SH ARGUMENTS
Takes xosd *osd as an argument, representing an XOSD object/on screen display window
.SH RETURN VALUE
Returns nscreens, which is the number of screen displays
.SH AUTHOR
libXosd team at Western Washington University