.\" Manpage for xosd_clone
.TH xosd_clone "2022-10-27" "X OSD Library"
.SH NAME
xosd_clone \- Duplicates an XOSD object with the same attributes
.SH SYNOPSIS
.B #include <xosd.h>
.sp
.BI "xosd* xosd_clone(xosd *osd2);
.fi
.SH DESCRIPTION
.B xosd_clone 
creates a new unique xosd object with the same attributes as the original xosd object.

.SH ARGUMENTS
.IP \fIosd2\fP 1i
The on-screen display object to duplicate.
.SH RETURN VALUE
On success, returns a new xosd object.
.SH AUTHOR
libXosd team at Western Washington University
