.\" Manpage for xosd_monitor.
.TH xosd_monitor "2022-10-27" "X OSD Library"
.SH NAME
xosd_monitor \- Repositions an xosd object around a specific physical monitor
.SH SYNOPSIS
int xosd_monitor(xosd * osd, int monitor)
.SH DESCRIPTION
xosd_monitor uses the provided monitor to shift the osd objects position and alignment information
.SH ARGUMENTS
.IP \fIosd\fP 1i
The on-screen display object to modify the monitor assigned. \n
.IP \fImonitor\fP 1i
The monitor to display the on-screen display object on, starting at 1 up to the number of connected monitors.
.SH RETURN VALUE
Returns 0 on success, -1 otherwise
.SH ERRORS
If an error occurs, xosd_monitor updates xosd_error, the global error string
.SH AUTHOR
libXosd team at Western Washington University

