.\" Manpage for xosd_monitor.
.TH xosd_monitor "2022-10-27" "X OSD Library"
.SH NAME
xosd_monitor \- captures the monitor and a display object for display
.SH SYNOPSIS
int xosd_monitor(xosd *osd, int monitor)
.SH DESCRIPTION
xosd_monitor uses the provided monitor and osd object to perform screen display
.SH ARGUMENTS
.IP \fIosd\fP 1i
the display object \n
.IP \fImonitor\fP 1i
the specific monitor of display
.SH RETURN VALUE
Returns 0 on success, -1 otherwise
.SH ERRORS
If an error occurs, xosd_monitor updates xosd_error, the global error string
.SH AUTHOR
libXosd team at Western Washington University

