.\" Manpage for xosd_set_shadow_direction.
.TH xosd_set_shadow_direction "2022-10-27" "X OSD Library"
.SH NAME
xosd_set_shadow_direction \- Set the direction of the shadow of the XODS window
.SH SYNOPSIS
.B #include <xosd.h>
.sp
.BI "int xosd_set_pos (xosd* " osd ", shadow_direction 
int xosd_set_shadow_direction(xosd *osd, int shadow_direction)
.SH DESCRIPTION
.B xosd_set_shadow_direction
changes the direction of the XOSD shadow from 0 to 7, 0 being upwards and rotating clockwise. The default direction is 3.
.SH ARGUMENTS
.IP \fIosd\fP 1i
The on-screen display object ot act on.
.IP \fIshadow_direction\fP 1i
Integer value from 0 to 7.
.SH RETURN VALUE
On a success, a zero is returned.
On error, \-1 is returned.
.SH "SEE ALSO"
.BR xosd_set_shadow_offset (3xosd)
