.\" Manpage for xosd_mlone
.TH xosd_clone "2022-10-27" "X OSD Library"
.SH NAME
xosd_clone \- creates a duplicate xosd object
.SH SYNOPSIS
xosd* xosd_clone(xosd *osd2)
.SH DESCRIPTION
xosd_clone creates a new xosd object with the same attributes as current xosd object
.SH ARGUMENTS
.IP \fIosd2\fP 1i
the xosd object to duplicate
.SH RETURN VALUE
Returns the duplicated xosd object
.SH AUTHOR
libXosd team at Western Washington University